.github/workflows/deploy.yml
=> fix : gihub action

.github/workflows/deploy.yml
=> feat : cd workflow redis 추가

docker-compose.yml, src/main/resources/application.yml
=> fix: 배포 관련 수정

src/main/java/kutaverse/game/websocket/map/MessageSender.java, src/main/java/kutaverse/game/websocket/map/dto/response/UserResponseDto.java, src/main/java/kutaverse/game/websocket/minigame/MatchingMaker.java
=> fix : schedule roll back

src/main/java/kutaverse/game/websocket/map/MessageSender.java
=> fix : schedule 변경

src/main/java/kutaverse/game/minigame/dto/ActorInfo.java, src/main/java/kutaverse/game/minigame/dto/MiniGameRequest.java
미니게임에 해당하는 클라이언트 요청사항 수정
1.  클라이언트 요청에 맞게 필드의 형식을 변경
=> [Refact] minigame request 요청 사항 수정

src/main/java/kutaverse/game/minigame/dto/ActorInfo.java, src/main/java/kutaverse/game/minigame/dto/MiniGameRequest.java, src/main/java/kutaverse/game/websocket/minigame/GameRoom.java, src/main/java/kutaverse/game/websocket/minigame/GameRoomManager.java, src/test/java/kutaverse/game/minigame/integration/MiniGameWebSocketTest.java
요구사항 들어온 것에 대한 변경 및 버그 수정
1. 상대가 탈주를 할 경우 해당 세션은 종료 되었지만 해당 세션에 계속해서 데이터를 보낼려고 하여 생기는 에러를 수정하였습니다.
2. 요구사항 중 필드 타입 추가와 변경이 있어 수정하였습니다.
- x
=> [Refact] minigame 버그 수정 및 요구사항 변경

src/main/java/kutaverse/game/websocket/map/MessageSender.java
=> fix: scheduler

.github/workflows/deploy.yml
=> fix: CD mysql

.github/workflows/deploy.yml, infra/docker/docker-compose.yml, src/main/resources/application.yml
=> fix: deploy

src/main/java/kutaverse/game/websocket/taggame/util/TagGameMatchingQueue.java
- 멀티게임 매칭이 미니게임 매칭으로 넘어가는 문제가 발생
1. 버그 수정
x
=> fix: tagGameMatchingQueue bug 수정

src/main/java/kutaverse/game/taggame/domain/TagGameUser.java, src/main/java/kutaverse/game/websocket/taggame/util/TagGameMatchingQueue.java
=> sleep 제거, 버그수정

src/main/java/kutaverse/game/taggame/domain/Status.java, src/main/java/kutaverse/game/taggame/domain/TagGameUser.java, src/main/java/kutaverse/game/websocket/taggame/dto/request/TagGameUserRequest.java, src/main/java/kutaverse/game/websocket/taggame/dto/response/TagGameUserResponse.java
술래게임 엔티티 변경
1. velocityXYZ 삭제
2. status 삭제
- 냉무
=> 술래게임 엔티티 변경

src/main/java/kutaverse/game/taggame/domain/TagGameUser.java
- TagGameUser 초기값 변경
1. null 값 상수값 변경
- 냉무
=> TagGameUser 초기값

src/main/java/kutaverse/game/taggame/domain/TagGameUser.java, src/main/java/kutaverse/game/taggame/service/TagGameUserService.java
- TagGameUser 초기값 변경
1. null 값 상수값 변경
- 냉무
=> fix: tagGameUser 초기값

src/main/java/kutaverse/game/websocket/chat/ChatWebSocketHandler.java
=> Chat broadcast 변경

src/test/java/kutaverse/game/DemoApplicationTests.java, src/test/java/kutaverse/game/map/integration/MapWebsocketTest.java, src/test/java/kutaverse/game/map/integration/UserControllerTest.java, src/test/java/kutaverse/game/map/integration/UserRepositoryTest.java, src/test/java/kutaverse/game/minigame/integration/MiniGameWebSocketTest.java, src/test/java/kutaverse/game/taggame/integration/TagGameWebsocketTest.java
=> [test] test 코드 수정

.github/workflows/deploy.yml
=> [cd] build시 환경 변수 주입

.github/workflows/deploy.yml
=> [fix] cd script 수정

src/main/resources/application.yml
=> [fix] 설정 파일 변경

.github/workflows/pr-test.yml, src/main/resources/application.yml, src/test/java/kutaverse/game/DemoApplicationTests.java, src/test/java/kutaverse/game/map/integration/MapWebsocketTest.java, src/test/java/kutaverse/game/map/integration/UserControllerTest.java, src/test/java/kutaverse/game/map/integration/UserRepositoryTest.java, src/test/java/kutaverse/game/minigame/integration/MiniGameWebSocketTest.java, src/test/java/kutaverse/game/taggame/integration/TagGameWebsocketTest.java
=> application.yml 수정

src/main/java/kutaverse/game/config/KafkaProducerConfig.java
=> [fix] producer 주소 변경

build.gradle, src/main/resources/application.yml
=> [feat] 프로메테우스 의존성 추가

src/main/java/kutaverse/game/websocket/taggame/dto/response/TagGameEndResponse.java, src/main/java/kutaverse/game/websocket/taggame/handler/TagGameEndHandler.java
=> [FIx] 게임 종료 response 추가
